// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGsXT5LSYJeILVZeeN2HwVpU8SH1UvoV4',
    appId: '1:425101553635:web:f6c8f9b6d56f60486fbad6',
    messagingSenderId: '425101553635',
    projectId: 'login-app-flutter-14a13',
    authDomain: 'login-app-flutter-14a13.firebaseapp.com',
    storageBucket: 'login-app-flutter-14a13.appspot.com',
    measurementId: 'G-KMKJMQCS9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjfqUMXxlfeIRwDBlUNyKvhVQ5BwKgeU4',
    appId: '1:425101553635:android:80519147770d416f6fbad6',
    messagingSenderId: '425101553635',
    projectId: 'login-app-flutter-14a13',
    storageBucket: 'login-app-flutter-14a13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDomd0YLvRT40NoRAhuPhldzpIMrYTcoc',
    appId: '1:425101553635:ios:ffa428c64b8a4aef6fbad6',
    messagingSenderId: '425101553635',
    projectId: 'login-app-flutter-14a13',
    storageBucket: 'login-app-flutter-14a13.appspot.com',
    iosClientId: '425101553635-nojoh3adgtsl6irl966avj23f3jah0pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDomd0YLvRT40NoRAhuPhldzpIMrYTcoc',
    appId: '1:425101553635:ios:ffa428c64b8a4aef6fbad6',
    messagingSenderId: '425101553635',
    projectId: 'login-app-flutter-14a13',
    storageBucket: 'login-app-flutter-14a13.appspot.com',
    iosClientId: '425101553635-nojoh3adgtsl6irl966avj23f3jah0pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );
}
